version: "3"

services:
  db:
    container_name: lapshope-mysql
    image: mysql
    networks:
      - lapshope-network
    restart: on-failure:3
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=lapshope
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./volumes/mysql:/var/lib/mysql
      # - ./dockerfiles/mysql/lapshope.initdb.sql:/docker-entrypoint-initdb.d/lapshope.initdb.sql

  phpmyadmin:
    container_name: lapshope-phpmyadmin
    image: phpmyadmin
    networks:
      - lapshope-network
    restart: on-failure:3
    ports:
      - 9997:80 
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=123456
    depends_on:
      - db

  redis:
    container_name: lapshope-redis
    image: redis
    networks:
      - lapshope-network
    restart: on-failure:3
    ports:
      - 6379:6379

  h2:
    container_name: lapshope-h2
    image: oscarfonts/h2
    networks: 
      - lapshope-network
    ports:
      - 8082:8082


networks:
  lapshope-network:
    name: lapshope-network
    driver: bridge
