
spring:
  application:
    name: LaptopStore

  datasource:
    url: jdbc:mysql://localhost:3306/lapshope
    username: root
    password: 123456

  web:
    resources:
      static-locations: classpath:/static/


  jpa:
    show-sql: true
    hibernate:
      # ddl-auto: update  # Uncomment if needed
      # ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ntriet0612@gmail.com
    password: hwpj vmai uqrq gvsq

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  jackson:
    time-zone: Asia/Ho_Chi_Minh


server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE


